name: get info

on:
  push:
  # allow manually trigger
  workflow_dispatch:

jobs:
  get-sarasa-gothic-info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: download latest version of Sarasa Gothic from GitHub release page
        run: |
          # find the latest tag
          LATEST_TAG=$(curl --silent https://api.github.com/repos/be5invis/Sarasa-Gothic/releases/latest | jq -r .tag_name)
          echo downloading Sarasa Gothic ${LATEST_TAG}
          curl -L https://github.com/be5invis/Sarasa-Gothic/releases/download/${LATEST_TAG}/sarasa-gothic-ttf-${LATEST_TAG:1}.7z -o sarasa-gothic-ttf.7z
      - run: ls -l
      - run: 7z x *.7z
      - run: ls -l
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: print info
        run: |
          pip install fonttools
          python ${GITHUB_WORKSPACE}/main.py > sarasa-gothic-output.txt
          python ${GITHUB_WORKSPACE}/main.py --dict > sarasa-gothic-dict-output.txt
      - uses: actions/upload-artifact@v2
        with:
          name: sarasa-gothic-output.txt
          path: sarasa-gothic-output.txt
      - uses: actions/upload-artifact@v2
        with:
          name: sarasa-gothic-dict-output.txt
          path: sarasa-gothic-dict-output.txt

  get-sarasa-nerd-fonts-info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: download latest version of Sarasa Gothic Nerd Fonts from GitHub release page
        run: |
          # find the latest tag
          LATEST_TAG=$(curl --silent https://api.github.com/repos/jonz94/Sarasa-Gothic-Nerd-Fonts/releases/latest | jq -r .tag_name)
          echo downloading Sarasa Gothic Nerd Fonts ${LATEST_TAG}

          styles=("fixed" "fixed-slab" "mono" "mono-slab" "term" "term-slab" "gothic" "ui")
          orthographies=("cl" "hc" "j" "k" "sc" "tc")
          for style in ${styles[@]}; do
            for orthography in ${orthographies[@]}; do
              curl -L "https://github.com/jonz94/Sarasa-Gothic-Nerd-Fonts/releases/download/${LATEST_TAG}/sarasa-${style}-${orthography}-nerd-font.zip" -O
            done
          done
      - run: ls -l
      - run: |
          styles=("fixed" "fixed-slab" "mono" "mono-slab" "term" "term-slab" "gothic" "ui")
          orthographies=("cl" "hc" "j" "k" "sc" "tc")
          for style in ${styles[@]}; do
            for orthography in ${orthographies[@]}; do
              unzip "sarasa-${style}-${orthography}-nerd-font.zip"
            done
          done
      - run: ls -l
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: print info
        run: |
          pip install fonttools
          python ${GITHUB_WORKSPACE}/main.py > sarasa-nerd-fonts-output.txt
          python ${GITHUB_WORKSPACE}/main.py --dict > sarasa-nerd-fonts-dict-output.txt
      - uses: actions/upload-artifact@v2
        with:
          name: sarasa-nerd-fonts-output.txt
          path: sarasa-nerd-fonts-output.txt
      - uses: actions/upload-artifact@v2
        with:
          name: sarasa-nerd-fonts-dict-output.txt
          path: sarasa-nerd-fonts-dict-output.txt
