name: get info

on:
  push:
  # allow manually trigger
  workflow_dispatch:

jobs:
  # get-sarasa-gothic-info:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: download latest version of Sarasa Gothic from GitHub release page
  #       run: |
  #         # find the latest tag
  #         LATEST_TAG=$(curl --silent https://api.github.com/repos/jonz94/Sarasa-Gothic-Nerd-Fonts/releases/latest | jq -r .tag_name)
  #         echo downloading Sarasa Mono TC Nerd Fonts ${LATEST_TAG}
  #         curl -L https://github.com/jonz94/Sarasa-Gothic-Nerd-Fonts/releases/download/${LATEST_TAG}/sarasa-mono-tc-nerd-font.zip -O
  #     - run: ls -l
  #     - run: unzip *.zip
  #     - run: ls -l
  #     - uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.x'
  #     - name: rename
  #       run: |
  #         # generate woff fonts using fonttools
  #         pip install fonttools
  #         python ${GITHUB_WORKSPACE}/main.py > output.txt
  #     - uses: actions/upload-artifact@v2
  #       with:
  #         name: output
  #         path: output.txt

  get-sarasa-nerd-fonts-info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: download latest version of Sarasa Gothic from GitHub release page
        run: |
          # find the latest tag
          LATEST_TAG=$(curl --silent https://api.github.com/repos/jonz94/Sarasa-Gothic-Nerd-Fonts/releases/latest | jq -r .tag_name)
          echo downloading Sarasa Gothic Nerd Fonts ${LATEST_TAG}

          styles=("fixed" "fixed-slab" "mono" "mono-slab" "term" "term-slab" "gothic" "ui")
          orthographies=("cl" "hc" "j" "k" "sc" "tc")
          for style in ${styles[@]}; do
            for orthography in ${orthographies[@]}; do
              curl -L "https://github.com/jonz94/Sarasa-Gothic-Nerd-Fonts/releases/download/${LATEST_TAG}/sarasa-${style}-${orthography}-nerd-font.zip" -O
            done
          done
      - run: ls -l
      - run: unzip *.zip
      - run: ls -l
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: rename
        run: |
          # generate woff fonts using fonttools
          pip install fonttools
          python ${GITHUB_WORKSPACE}/main.py > sarasa-nerd-fonts-output.txt
      - uses: actions/upload-artifact@v2
        with:
          name: sarasa-nerd-fonts-output.txt
          path: sarasa-nerd-fonts-output.txt
